"""full schema baseline

Revision ID: 53be9adf87bb
Revises: d4e5f6g7h8i9
Create Date: 2026-03-12 07:43:20.479556
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '53be9adf87bb'
down_revision: Union[str, None] = 'd4e5f6g7h8i9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('channel_schedules', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_channel_schedules_channel_id'), 'channel_schedules', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_schedules_id'), 'channel_schedules', ['id'], unique=False)
    op.drop_constraint(None, 'channel_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'channel_schedules', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.alter_column('channel_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_channel_sessions_channel_id'), 'channel_sessions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_sessions_id'), 'channel_sessions', ['id'], unique=False)
    op.create_unique_constraint('uq_channel_session', 'channel_sessions', ['channel_id', 'sender_id'])
    op.drop_constraint(None, 'channel_sessions', type_='foreignkey')
    op.drop_constraint(None, 'channel_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'channel_sessions', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'channel_sessions', 'chat_conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    op.alter_column('channels', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('channels', 'config',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.create_index(op.f('ix_channels_user_id'), 'channels', ['user_id'], unique=False)
    op.create_index(op.f('ix_channels_workspace_id'), 'channels', ['workspace_id'], unique=False)
    op.create_unique_constraint(None, 'channels', ['webhook_token'])
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.create_foreign_key(None, 'channels', 'knowledge_bases', ['kb_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'channels', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'channels', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'channels', 'model_configs', ['llm_model_id'], ['id'], ondelete='SET NULL')
    op.alter_column('chat_conversations', 'total_input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chat_conversations', 'total_output_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chat_messages', 'msg_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'chat'"))
    op.drop_column('database_sources', 'sqlite_path')
    op.alter_column('database_sync_runs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('database_sync_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', name='syncrunstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'running'"))
    op.alter_column('database_sync_runs', 'duration_seconds',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_database_sync_runs_id'), 'database_sync_runs', ['id'], unique=False)
    op.drop_constraint(None, 'database_sync_runs', type_='foreignkey')
    op.create_foreign_key(None, 'database_sync_runs', 'database_sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.alter_column('mcp_server_configs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'mcp_server_configs', type_='foreignkey')
    op.drop_constraint(None, 'mcp_server_configs', type_='foreignkey')
    op.create_foreign_key(None, 'mcp_server_configs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'mcp_server_configs', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.alter_column('model_configs', 'provider',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('OPENAI', 'ANTHROPIC', 'OLLAMA', 'CUSTOM', name='modelprovider'),
               existing_nullable=False)
    op.alter_column('skill_installs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_unique_constraint('uq_user_skill_ws', 'skill_installs', ['user_id', 'skill_id', 'workspace_id'])
    op.drop_constraint(None, 'skill_installs', type_='foreignkey')
    op.drop_constraint(None, 'skill_installs', type_='foreignkey')
    op.drop_constraint(None, 'skill_installs', type_='foreignkey')
    op.create_foreign_key(None, 'skill_installs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'skill_installs', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'skill_installs', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.alter_column('skills', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'skills', ['slug'])
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.create_foreign_key(None, 'skills', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user_memories', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('user_memories', 'embedding',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    op.drop_constraint(None, 'user_memories', type_='foreignkey')
    op.create_foreign_key(None, 'user_memories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    op.alter_column('workspace_invitations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('workspace_invitations', 'role',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='workspacerole'),
               existing_nullable=False,
               existing_server_default=sa.text("'member'"))
    op.create_index(op.f('ix_workspace_invitations_id'), 'workspace_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_invitations_invite_token'), 'workspace_invitations', ['invite_token'], unique=True)
    op.create_index(op.f('ix_workspace_invitations_workspace_id'), 'workspace_invitations', ['workspace_id'], unique=False)
    op.drop_constraint(None, 'workspace_invitations', type_='foreignkey')
    op.drop_constraint(None, 'workspace_invitations', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_invitations', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workspace_invitations', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_workspace_member', 'workspace_members', ['workspace_id', 'user_id'])
    op.alter_column('workspace_model_configs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_workspace_model_configs_id'), 'workspace_model_configs', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_model_configs_model_config_id'), 'workspace_model_configs', ['model_config_id'], unique=False)
    op.create_index(op.f('ix_workspace_model_configs_workspace_id'), 'workspace_model_configs', ['workspace_id'], unique=False)
    op.drop_constraint(None, 'workspace_model_configs', type_='foreignkey')
    op.drop_constraint(None, 'workspace_model_configs', type_='foreignkey')
    op.drop_constraint(None, 'workspace_model_configs', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_model_configs', 'model_configs', ['model_config_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace_model_configs', 'users', ['shared_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workspace_model_configs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_model_configs', type_='foreignkey')
    op.drop_constraint(None, 'workspace_model_configs', type_='foreignkey')
    op.drop_constraint(None, 'workspace_model_configs', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_model_configs', 'users', ['shared_by'], ['id'])
    op.create_foreign_key(None, 'workspace_model_configs', 'model_configs', ['model_config_id'], ['id'])
    op.create_foreign_key(None, 'workspace_model_configs', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index(op.f('ix_workspace_model_configs_workspace_id'), table_name='workspace_model_configs')
    op.drop_index(op.f('ix_workspace_model_configs_model_config_id'), table_name='workspace_model_configs')
    op.drop_index(op.f('ix_workspace_model_configs_id'), table_name='workspace_model_configs')
    op.alter_column('workspace_model_configs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('uq_workspace_member', 'workspace_members', type_='unique')
    op.drop_constraint(None, 'workspace_invitations', type_='foreignkey')
    op.drop_constraint(None, 'workspace_invitations', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_invitations', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'workspace_invitations', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_workspace_invitations_workspace_id'), table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_invite_token'), table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_id'), table_name='workspace_invitations')
    op.alter_column('workspace_invitations', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='workspacerole'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'member'"))
    op.alter_column('workspace_invitations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('users', 'must_change_password')
    op.drop_constraint(None, 'user_memories', type_='foreignkey')
    op.create_foreign_key(None, 'user_memories', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.alter_column('user_memories', 'embedding',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_memories', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.create_foreign_key(None, 'skills', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'skills', type_='unique')
    op.alter_column('skills', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'skill_installs', type_='foreignkey')
    op.drop_constraint(None, 'skill_installs', type_='foreignkey')
    op.drop_constraint(None, 'skill_installs', type_='foreignkey')
    op.create_foreign_key(None, 'skill_installs', 'skills', ['skill_id'], ['id'])
    op.create_foreign_key(None, 'skill_installs', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'skill_installs', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_user_skill_ws', 'skill_installs', type_='unique')
    op.alter_column('skill_installs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('model_configs', 'provider',
               existing_type=sa.Enum('OPENAI', 'ANTHROPIC', 'OLLAMA', 'CUSTOM', name='modelprovider'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.drop_constraint(None, 'mcp_server_configs', type_='foreignkey')
    op.drop_constraint(None, 'mcp_server_configs', type_='foreignkey')
    op.create_foreign_key(None, 'mcp_server_configs', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'mcp_server_configs', 'users', ['user_id'], ['id'])
    op.alter_column('mcp_server_configs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'database_sync_runs', type_='foreignkey')
    op.create_foreign_key(None, 'database_sync_runs', 'database_sources', ['source_id'], ['id'])
    op.drop_index(op.f('ix_database_sync_runs_id'), table_name='database_sync_runs')
    op.alter_column('database_sync_runs', 'duration_seconds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('database_sync_runs', 'status',
               existing_type=sa.Enum('RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', name='syncrunstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'running'"))
    op.alter_column('database_sync_runs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('database_sources', sa.Column('sqlite_path', sa.VARCHAR(length=1000), nullable=True))
    op.alter_column('chat_messages', 'msg_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'chat'"))
    op.alter_column('chat_conversations', 'total_output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('chat_conversations', 'total_input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.create_foreign_key(None, 'channels', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'channels', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'channels', 'knowledge_bases', ['kb_id'], ['id'])
    op.create_foreign_key(None, 'channels', 'model_configs', ['llm_model_id'], ['id'])
    op.drop_constraint(None, 'channels', type_='unique')
    op.drop_index(op.f('ix_channels_workspace_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_user_id'), table_name='channels')
    op.alter_column('channels', 'config',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('channels', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'channel_sessions', type_='foreignkey')
    op.drop_constraint(None, 'channel_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'channel_sessions', 'chat_conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'channel_sessions', 'channels', ['channel_id'], ['id'])
    op.drop_constraint('uq_channel_session', 'channel_sessions', type_='unique')
    op.drop_index(op.f('ix_channel_sessions_id'), table_name='channel_sessions')
    op.drop_index(op.f('ix_channel_sessions_channel_id'), table_name='channel_sessions')
    op.alter_column('channel_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'channel_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'channel_schedules', 'channels', ['channel_id'], ['id'])
    op.drop_index(op.f('ix_channel_schedules_id'), table_name='channel_schedules')
    op.drop_index(op.f('ix_channel_schedules_channel_id'), table_name='channel_schedules')
    op.alter_column('channel_schedules', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('api_keys', 'key',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
